name: Frontend CI

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: frontend

jobs:
  testing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use NodeJS LTS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Installation
        run: npm ci
      - name: Building
        run: npm run build
      - name: Linting
        run: npm run check
      - name: Testing
        run: npm run test
        env:
          CI: true
      - name: Bump new version
        run: |
          npm run bump -- -v ${{ github.event.release.tag_name }}
          git commit -m "chore(release): ${{ github.event.release.tag_name }}"
          git push
        env:
          GIT_AUTHOR_NAME: Vaadin Bot
          GIT_AUTHOR_EMAIL: vaadin-bot@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}







