name: Validation

on:
  push:
    branches: [ main, '2.1', '2.0', '1.3' ]
    paths:
      - 'hilla-logo.svg'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
      - 'packages/**/README.md'
  pull_request_target:
    paths:
      - 'hilla-logo.svg'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
      - 'packages/**/README.md'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          username: ${{github.triggering_actor}}
          require: 'write'
      - name: Fail on external workflow triggering
        if: ${{ steps.checkUser.outputs.require-result != 'true' }}
        run: |
          echo "🚫 **${{ github.actor }}** is an external contributor, a **${{github.repository}}** team member has to review this changes and re-run this build" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1
      - name: Check secrets
        run: |
          [ -z "${{secrets.TB_LICENSE}}" ] \
            && echo "🚫 **TB_LICENSE** is not defined, check that **${{github.repository}}** repo has a valid secret" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1 || exit 0

  test-all:
    name: Tests Summary
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: 'echo "No build required"'
